### ISSUE TITLE
Allow passing your own json to the program

### ISSUE THREAD

**Issue by rafagarcia** [kasselTrankos/funcpine#2]
It would be great if the program accept any external json.
Congrats for the work.

**Comment by kasselTrankos** [comment]
You can change the content of demo/file.json, to load any json. Or your idea is load any url json?, not a file?

**Comment by rafagarcia** [comment]
To load it dinamically, loading a remote url, uploading a json file...

**Comment by kasselTrankos** [comment]
Given an interface to user, to do it. Ok. And leave default as it's done

**Comment by kasselTrankos** [comment]
Hi, this commit b8dece4e70b7d8f7fead7e06da7eadbb8741bf61, got load dynamically from local machine. Next from URI,

**Comment by kasselTrankos** [comment]
Done search by url, there is a check on the right at button thats show or hide the type of load 1b616546b9f1d4691e0f848f07ee381734a4f39c

**Comment by kasselTrankos** [comment]
i belive this is better solution, making over in header title show selector for other json file ecaf7025a64a426684977fdf647b4d477f29cc4d

**Comment by kasselTrankos** [comment]
Give solutionated by this commit. 493412db019141153d339a56e23b50381b592825
